### ISSUE TITLE
Electron fails to start on Windows

### ISSUE THREAD

**Issue by mateon1** [diasdavid/go-ipfs-dep#10]
Even if the build issue on Windows is fixed, a new issue appears.
When running `npm start`:

```
> orbit@3.2.0 start C:\Users\matin\orbit
> npm run electron


> orbit@3.2.0 electron C:\Users\matin\orbit
> electron .

fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\matin\orbit\node_modules\electron-prebuilt\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.<anonymous> (C:\Users\matin\orbit\node_modules\electron-prebuilt\index.js:4:42)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)

npm ERR! Windows_NT 10.0.14936
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "electron"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! orbit@3.2.0 electron: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the orbit@3.2.0 electron script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the orbit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs orbit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls orbit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\matin\orbit\npm-debug.log

npm ERR! Windows_NT 10.0.14936
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! orbit@3.2.0 start: `npm run electron`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the orbit@3.2.0 start script 'npm run electron'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the orbit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run electron
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs orbit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls orbit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\matin\orbit\npm-debug.log
```

There is nothing interesting in `npm-debug.log`.

**Comment by mateon1** [comment]
I'm sorry, I posted this in the wrong repo. This belongs to Orbit.
